Web/Controllers/AuthorizeController.cs
using Domains.Domains;
using Domains.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Repository.Repositories;
using System.Security.Claims;

namespace Web.Controllers {
    public class AuthorizeController : Controller {
        private readonly UserRepository _userRepository;

        public AuthorizeController(UserRepository userRepository) {
            _userRepository = userRepository;
        }

        public IActionResult SignUp() {
            return View();
        }

        public IActionResult LogIn() {
            return View();
        }

        [HttpPost]
        public IActionResult LogIn(LoginModel model) {
            if (ModelState.IsValid) {
                var user = _userRepository.GetByLogin(model.Login);
                if (user == null) {
                    ModelState.AddModelError(string.Empty, $"{model.Login} is not exist");
                }
                else if (!_userRepository.CheckPassword(user, model.Password)) {
                    ModelState.AddModelError(string.Empty, $"Password is wrong");
                }
                else {
                    AutorizeUser(model.Login);
                    return RedirectToAction("Index", "PasswordInfo");
                }
            }
            return View("Index", model);
        }

        [HttpPost]
        public IActionResult SignUp(RegisterModel model) {
            if (model.Password != model.RepeatPassword) {
                ModelState.AddModelError(string.Empty, "Password is not equal repeat password");
            }
            if (_userRepository.IsLoginExist(model.Login)) {
                ModelState.AddModelError(string.Empty, $"{model.Login} is exist");
            }
            else if (ModelState.IsValid) {
                AutorizeUser(model.Login);

                var newUser = new User() {
                    Login = model.Login,
                    Password = model.Password,
                    ConfirmCode = model.ConfirmCode
                };

                _userRepository.Add(newUser);
                return RedirectToAction("Index", "PasswordInfo");
            }
            return View("Index", model);
        }

        public IActionResult Logout() {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        private void AutorizeUser(string login) {
            var claims = new List<Claim> { new Claim(ClaimTypes.Name, login) };
            var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var principal = new ClaimsPrincipal(identity);
            HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
        }
    }
}

Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers {
    public class HomeController : Controller {
        public IActionResult Index() {
            return View();
        }
    }
}

Web/Controllers/PasswordGeneratorController.cs
using Domains.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Servicies.PasswordGenerator;
using Web.Servicies;

namespace Web.Controllers {
    public class PasswordGeneratorController : Controller {
        private readonly CookieManager _cookieManager;

        public PasswordGeneratorController(CookieManager cookieManager) {
            _cookieManager = cookieManager;
        }

        public IActionResult Index() {
            var model = _cookieManager.GetCookie<PasswordGeneratorModel>(HttpContext.Request.Cookies , "passwordGenerator");
            return View(model);
        }

        [HttpPost]
        public IActionResult Index(PasswordGeneratorModel model) {
            _cookieManager.SetCookie(model, HttpContext.Response.Cookies, "passwordGenerator");

            var generator = new PasswordGenerator(model);
            try {
                generator.Generate();
            }
            catch (Exception e){
                model.Password = e.Message;
            }

            return View(model);
        }
    }
}

Web/Controllers/PasswordInfoController.cs
using Domains.Domains;
using Domains.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Repository.Repositories;
using System.Text.Json;
using Web.Servicies;

namespace Web.Controllers {
    [Authorize]
    public class PasswordInfoController : Controller {
        private readonly PasswordInfoRepository _passwordInfoRepository;
        private readonly UserRepository _userRepository;
        private readonly CookieManager _cookieManager;

        public PasswordInfoController(
            PasswordInfoRepository passwordInfoRepository,
            UserRepository userRepository,
            CookieManager cookieManager) {
            _passwordInfoRepository = passwordInfoRepository;
            _userRepository = userRepository;
            _cookieManager = cookieManager;
        }

        public IActionResult Index() {
            var searchModel = _cookieManager.GetCookie<SearchModel>(HttpContext.Request.Cookies, "search");
            var model = GetPasswordListModel();
            model.SearchModel = searchModel;
            model.PasswordInfos = model.PasswordInfos
                .Where(e => string.IsNullOrEmpty(searchModel.ServiceName) || e.ServiceName.Contains(searchModel.ServiceName));

            return View(model);
        }

        [HttpPost]
        public IActionResult Index(SearchModel searchModel) {
            _cookieManager.SetCookie(searchModel, HttpContext.Response.Cookies, "search");
            var model = GetPasswordListModel();
            model.SearchModel = searchModel;
            model.PasswordInfos = model.PasswordInfos
                .Where(e => string.IsNullOrEmpty(searchModel.ServiceName) || e.ServiceName.Contains(searchModel.ServiceName));

            return View(model);
        }

        public IActionResult Add() {
            return View();
        }

        [HttpPost]
        public IActionResult Add(PasswordInfoModel model) {
            var currentUser = _userRepository.GetByLogin(User.Identity.Name);
            var newPasswordInfo = new PasswordInfo() {
                ServiceName = model.ServiceName,
                Login = model.Login,
                UserId = currentUser.Id,
                User = currentUser,
                Password = model.Password,
                Description = model.Description
            };
            _passwordInfoRepository.Add(newPasswordInfo);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id) {
            var passwordInfo = _passwordInfoRepository.GetById(id);
            _passwordInfoRepository.Remove(passwordInfo);
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id) {
            var model = _passwordInfoRepository.GetById(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(PasswordInfo model) {
            var currentUser = _userRepository.GetByLogin(User.Identity.Name);
            model.User = currentUser;
            model.UserId = currentUser.Id;
            _passwordInfoRepository.Update(model);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public FileResult ExportJson() {
            var currentUser = _userRepository.GetByLogin(User.Identity.Name);
            var passwordInfos = _passwordInfoRepository.GetPasswordInfosByUser(currentUser);
            string json = JsonSerializer.Serialize(passwordInfos);
            var bytes = System.Text.Encoding.UTF8.GetBytes(json);
            return File(bytes, "application/json", "passwords.json");
        }

        private PasswordListModel GetPasswordListModel() {
            var currentUser = _userRepository.GetByLogin(User.Identity.Name);
            var passwordInfos = _passwordInfoRepository.GetPasswordInfosByUser(currentUser);
            var model = new PasswordListModel() {
                PasswordInfos = passwordInfos,
                ConfirmCode = currentUser.ConfirmCode
            };
            return model;
        }
    }
}

Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers {
    public class UserController : Controller {
        public IActionResult Index() {
            return View();
        }
    }
}

Web/Views/Authorize/LogIn.cshtml
@using Domains.ViewModels
@model LoginModel;
@{
    ViewData["Title"] = "Log In";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="display-4 text-primary text-center">Log In</h1>
<div class="row d-flex justify-content-center mb-2">
    <div class="col-md-4">
        <form asp-action="LogIn">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-floating mb-3">
                <input asp-for="Login" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.Login)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.Login)" />
                <label asp-for="Login">@Html.DisplayNameFor(model => model.Login)</label>
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Password" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.Password)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.Password)" />
                <label asp-for="Password">@Html.DisplayNameFor(model => model.Password)</label>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <input type="submit" value="Log In" class="w-100 btn btn-lg btn-primary mt-2" />
        </form>
    </div>
</div>

Web/Views/Authorize/SignUp.cshtml
@using Domains.ViewModels
@model RegisterModel;
@{
    ViewData["Title"] = "Sign Up";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="display-4 text-primary text-center">Sign Up</h1>
<div class="row d-flex justify-content-center mb-2">
    <div class="col-md-4">
        <form asp-action="SignUp">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-floating mb-3">
                <input asp-for="Login" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.Login)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.Login)" />
                <label asp-for="Login">@Html.DisplayNameFor(model => model.Login)</label>
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Password" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.Password)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.Password)" />
                <label asp-for="Password">@Html.DisplayNameFor(model => model.Password)</label>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="RepeatPassword" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.RepeatPassword)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.RepeatPassword)" />
                <label asp-for="RepeatPassword">@Html.DisplayNameFor(model => model.RepeatPassword)</label>
                <span asp-validation-for="RepeatPassword" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="ConfirmCode" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.ConfirmCode)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.ConfirmCode)" />
                <label asp-for="ConfirmCode">@Html.DisplayNameFor(model => model.ConfirmCode)</label>
                <span asp-validation-for="ConfirmCode" class="text-danger"></span>
            </div>

            <input type="submit" value="Sign Up" class="w-100 btn btn-lg btn-primary mt-2" />
        </form>
    </div>
</div>

Web/Views/Home/Index.cshtml
@using Domains.ViewModels
@model PasswordInfoModel;
@{
    ViewData["Title"] = "Main Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="display-4 text-primary text-center">Password Manager</h1>

Web/Views/LogIn/Index.cshtml
@using Domains.ViewModels
@model LoginModel;
@{
    ViewData["Title"] = "Log In";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="display-4 text-primary text-center">Log In</h1>
<div class="row d-flex justify-content-center mb-2">
    <div class="col-md-4">
        <form asp-action="LogIn">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-floating mb-3">
                <input asp-for="Login" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.Login)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.Login)" />
                <label asp-for="Login">@Html.DisplayNameFor(model => model.Login)</label>
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Password" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.Password)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.Password)" />
                <label asp-for="Password">@Html.DisplayNameFor(model => model.Password)</label>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <input type="submit" value="Log In" class="w-100 btn btn-lg btn-primary mt-2" />
        </form>
    </div>
</div>

Web/Views/PasswordGenerator/Index.cshtml
@using Domains.ViewModels
@model PasswordGeneratorModel
@{
    ViewData["Title"] = "Password Generator";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1 class="display-4 text-primary text-center font-weight-bold">Password Generator</h1>
<form asp-action="Index" method="post">
    <div class="input-group mb-3 mx-auto" style="max-width: 50rem;">
        <input asp-for="Password" value="@Model.Password" class="form-control form-control-lg" placeholder="@Html.DisplayNameFor(e => e.Password)" aria-label="@Html.DisplayNameFor(e => e.Password)" aria-describedby="button-addon2">
        <button class="btn btn-primary" type="submit" id="button-addon2">Generate</button>
    </div>
    <div class="card border-primary mb-3 mx-auto" style="max-width: 50rem;">
        <div class="card-header text-center text-primary">
            <h1>
                Settings
            </h1>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-8">
                    <h4 class="text-center text-primary mb-0 text-lg">@Html.DisplayNameFor(e => e.Length)</h4>
                </div>
                <div class="col-md-4">
                    <input asp-for="Length" type="number" min="1" max="64" class="form-control pt-0" autocomplete="@Html.DisplayNameFor(model => model.Length)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.Length)" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <h5 class="text-center text-primary">@Html.DisplayNameFor(e => e.UseDigits)</h5>
                </div>
                <div class="col-md-1 form-check form-check-lg form-switch">
                    <input asp-for="UseDigits" type="checkbox" class="form-check-input" autocomplete="@Html.DisplayNameFor(model => model.UseDigits)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.UseDigits)" />
                </div>
                <div class="col-md-5">
                    <h5 class="text-center text-primary">@Html.DisplayNameFor(e => e.UseLowercase)</h5>
                </div>
                <div class="col-md-1 form-check form-check-lg form-switch">
                    <input asp-for="UseLowercase" type="checkbox" class="form-check-input" autocomplete="@Html.DisplayNameFor(model => model.UseLowercase)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.UseLowercase)" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <h5 class="text-center text-primary">@Html.DisplayNameFor(e => e.UseUppercase)</h5>
                </div>
                <div class="col-md-1 form-check form-check-lg form-switch">
                    <input asp-for="UseUppercase" type="checkbox" class="form-check-input" autocomplete="@Html.DisplayNameFor(model => model.UseUppercase)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.UseUppercase)" />
                </div>
                <div class="col-md-5">
                    <h5 class="text-center text-primary">@Html.DisplayNameFor(e => e.UseSymbols)</h5>
                </div>
                <div class="col-md-1 form-check form-check-lg form-switch">
                    <input asp-for="UseSymbols" type="checkbox" class="form-check-input" autocomplete="@Html.DisplayNameFor(model => model.UseSymbols)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.UseSymbols)" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <h5 class="text-center text-primary">@Html.DisplayNameFor(e => e.UseUnique)</h5>
                </div>
                <div class="col-md-1 form-check form-check-lg form-switch">
                    <input asp-for="UseUnique" type="checkbox" class="form-check-input" autocomplete="@Html.DisplayNameFor(model => model.UseUnique)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.UseUnique)" />
                </div>
                <div class="col-md-5">
                    <h5 class="text-center text-primary">@Html.DisplayNameFor(e => e.DontUseExcludeSimilar)</h5>
                </div>
                <div class="col-md-1 form-check form-check-lg form-switch">
                    <input asp-for="DontUseExcludeSimilar" type="checkbox" class="form-check-input" autocomplete="@Html.DisplayNameFor(model => model.DontUseExcludeSimilar)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.DontUseExcludeSimilar)" />
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    var slider = document.getElementById("lenghtRanger");
    var inputField = document.getElementById("lenghtField");

    slider.addEventListener("input", function () {
        inputField.value = slider.value;
    });
</script>

Web/Views/PasswordInfo/Add.cshtml
@using Domains.ViewModels
@model PasswordInfoModel;
@{
    ViewData["Title"] = "Add Password Info";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="display-4 text-primary text-center">Add Password</h1>
<div class="row d-flex justify-content-center mb-2">
    <div class="col-md-4">
        <form asp-action="Add" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-floating mb-3">
                <input asp-for="ServiceName" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.ServiceName)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.ServiceName)" />
                <label asp-for="ServiceName">@Html.DisplayNameFor(model => model.ServiceName)</label>
                <span asp-validation-for="ServiceName" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Login" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.Login)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.Login)" />
                <label asp-for="Login">@Html.DisplayNameFor(model => model.Login)</label>
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Description" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.Description)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.Description)" />
                <label asp-for="Description">@Html.DisplayNameFor(model => model.Description)</label>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Password" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.Password)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.Password)" />
                <label asp-for="Password">@Html.DisplayNameFor(model => model.Password)</label>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <input type="submit" value="Add" class="w-100 btn btn-lg btn-primary mt-2" />
        </form>
    </div>
</div>

Web/Views/PasswordInfo/Index.cshtml
@using Domains.ViewModels
@using Web.Utilies
@model PasswordListModel;
@{
    ViewData["Title"] = "Password List";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int i = 1;
}
<h1 class="display-4 text-primary text-center font-weight-bold">Password List</h1>
<form asp-action="Index" method="post">
    <div class="input-group mb-3">
        <input type="text" name="serviceName" value="@Model.SearchModel.ServiceName" class="form-control" placeholder="Service Name" aria-label="Service Name" aria-describedby="button-addon2">
        <button class="btn btn-primary" type="submit" id="button-addon2">Search</button>
    </div>
</form>

<div class="row d-flex mb-2">
    @foreach(var passwordInfo in Model.PasswordInfos) {
        <div class="col-md-4">
            <div class="card text-white bg-primary mb-3" style="max-width: 40rem;">
                <div class="card-header text-center">
                    <h3>
                        @passwordInfo.ServiceName
                    </h3>
                </div>
                <div class="card-body">
                    <h4 class="card-title">Login: @passwordInfo.Login</h4>
                    <p class="card-text">Description: @passwordInfo.Description</p>
                    <input type="password" id="inputField_@i" class="form-control" autocomplete="Confirm Code" aria-required="true" placeholder="Confirm Code" />
                    <h4 id="password_@i" class="card-text hidden text-center">@passwordInfo.Password</h4>
                </div>
                <div class="card-footer justify-content-center">
                    <a id="edit_@i" class="text-decoration-none text-white mx-1 hidden" asp-action="Update" asp-route-id="@passwordInfo.Id">
                        @Html.EditIcon(28, 28)
                    </a>
                    <a id="delete_@i" class="text-decoration-none text-white mx-1 hidden" asp-action="Delete" asp-route-id="@passwordInfo.Id">
                        @Html.DeleteIcon(28, 28)
                    </a>
                </div>
            </div>
        </div>
        i++;
    }
</div>

<form asp-action="ExportJson" method="post">
    <input type="password" id="exportField" class="form-control w-25" autocomplete="Confirm Code" aria-required="true" placeholder="Confirm Code" />
    <button class="btn btn-primary hidden" id="exportSubmit" type="submit">Export to Json</button>
</form>


<script>
    document.addEventListener('DOMContentLoaded', function () {
        var inputCount = @Model.PasswordInfos.Count();
        for (var i = 1; i <= inputCount; i++) {
            var inputField = document.getElementById('inputField_' + i);
            var editButton = document.getElementById('edit_' + i);
            var deleteButton = document.getElementById('delete_' + i);
            var passwordLabel = document.getElementById('password_' + i);
            inputField.addEventListener('input', createInputHandler(inputField, passwordLabel, editButton, deleteButton));
        }
        var exportField = document.getElementById('exportField');
        var exportSubmit = document.getElementById('exportSubmit');
        exportField.addEventListener('input', exportInputHandler(exportField, exportSubmit));
    });

    function createInputHandler(inputField, passwordLabel, editButton, deleteButton) {
        return function () {
            if (inputField.value.trim() == @Model.ConfirmCode) {
                passwordLabel.classList.remove('hidden');
                editButton.classList.remove('hidden');
                deleteButton.classList.remove('hidden');
                inputField.classList.add('hidden');
            }
        };
    }

    function exportInputHandler(exportField, exportSubmit) {
        return function () {
            if (exportField.value.trim() == @Model.ConfirmCode) {
                exportSubmit.classList.remove('hidden');
                exportField.classList.add('hidden');
            }
        };
    }
</script>

Web/Views/PasswordInfo/Update.cshtml
@using Domains.Domains
@model PasswordInfo;
@{
    ViewData["Title"] = "Update Password Info";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="display-4 text-primary text-center">Update Password</h1>
<div class="row d-flex justify-content-center mb-2">
    <div class="col-md-4">
        <form asp-action="Update" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-floating mb-3">
                <input asp-for="ServiceName" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.ServiceName)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.ServiceName)" />
                <label asp-for="ServiceName">@Html.DisplayNameFor(model => model.ServiceName)</label>
                <span asp-validation-for="ServiceName" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Login" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.Login)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.Login)" />
                <label asp-for="Login">@Html.DisplayNameFor(model => model.Login)</label>
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Description" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.Description)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.Description)" />
                <label asp-for="Description">@Html.DisplayNameFor(model => model.Description)</label>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Password" class="form-control" autocomplete="@Html.DisplayNameFor(model => model.Password)" aria-required="true" placeholder="@Html.DisplayNameFor(model => model.Password)" />
                <label asp-for="Password">@Html.DisplayNameFor(model => model.Password)</label>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <input type="submit" value="Update" class="w-100 btn btn-lg btn-primary mt-2" />
        </form>
    </div>
</div>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-action="Index" asp-controller="Home">Password Manager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Index" asp-controller="PasswordInfo">Password List</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Add" asp-controller="PasswordInfo">Add Password</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="PasswordGenerator">Password Generator</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav d-flex">
                        @if (User.Identity.IsAuthenticated) {
                            <li class="nav-item">
                                <p class="nav-link">@User.Identity.Name</p>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="Logout" asp-controller="Authorize">Log Out</a>
                            </li>
                        }
                        else {
                            <li class="nav-item">
                                <a class="nav-link" asp-action="LogIn" asp-controller="Authorize">Log In</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-action="SignUp" asp-controller="Authorize">Sign Up</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PasswordManager
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>